test_that("use", {
  expect_false(is_on_rackham_login_node())
  expect_true(is_on_rackham_login_node(host_name = "rackham3.uppmax.uu.se"))
  expect_false(is_on_rackham_login_node(host_name = "r1"))
  expect_false(is_on_rackham_login_node(host_name = "r12"))
  expect_false(is_on_rackham_login_node(host_name = "r123"))
  expect_false(is_on_rackham_login_node(host_name = "r1234"))
  expect_false(is_on_rackham_login_node(host_name = "nonsense"))
  expect_error(is_on_rackham_login_node(host_name = NA))
  expect_error(is_on_rackham_login_node(host_name = NULL))
  expect_error(is_on_rackham_login_node(host_name = Inf))
  expect_error(is_on_rackham_login_node(host_name = 42))
  expect_error(is_on_rackham_login_node(host_name = c("r1", "r12")))
})
