on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      #- name: Install libpoppler-cpp-dev
      #  run: sudo apt install -qq libpoppler-cpp-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("MangoTheCat/goodpractice")
        shell: Rscript {0}

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Measure coverage
        run: Rscript -e "covr::codecov()"

      - name: Lint
        run: Rscript -e "lintr::lint_package()"

      - name: Good practices
        run: Rscript -e "goodpractice::gp()"

